export const DETAIL_ROUTES = {
    DEFAULT: 'details',
    GET_DEFAULT_CHARACTERISTICS_BY_ROOM_TYPE: 'characteristics/default/:roomTypeId',
    GET_SECTIONS_AND_CHARS_BY_ROOM_TYPE: 'sections_n_chars/:roomTypeId',
    GET_ALL_CHARACTERISTICS: 'characteristics',
    GET_CHARACTERISTIC: 'characteristics/:id',
    CREATE_CHARACTERISTIC: 'characteristics',
    UPDATE_CHARACTERISTIC: 'characteristics/:id',
    GET_ALL_ATTRIBUTES: 'attributes',
    GET_ATTRIBUTE: 'attributes/:id',
    CREATE_ATTRIBUTE: 'attributes',
    UPDATE_ATTRIBUTE: 'attributes/:id',
    GET_ALL_ROOM_TYPES: 'room_types',
    GET_ROOM_TYPE: 'attributes/:id',
    CREATE_ROOM_TYPE: 'room_types',
    UPDATE_ROOM_TYPE: 'room_types/:id',
    GET_ALL_SECTION_TYPES: 'section_types',
    GET_SECTION_TYPE: 'attributes/:id',
    CREATE_SECTION_TYPE: 'section_types',
    UPDATE_SECTION_TYPE: 'section_types/:id',
} satisfies Record<string, string>;
