export const AUTH_ERRORS = {
    PASSWORDS_ARE_NOT_EQUAL: 'INCORRECT_PASSWORD',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    UNAUTHORIZED: 'USER_UNAUTHORIZED',
    INVALID_EMAIL: 'INVALID_EMAIL',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
};
