export const AUTH_ERRORS = {
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    UNAUTHORIZED: 'USER_UNAUTHORIZED',
    FORBIDDEN: 'USER_FORBIDDEN',
    INVALID_EMAIL: 'INVALID_EMAIL',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
};
