export const DOCUMENTS_ERRORS = {
    CMS_IS_MISSED: 'CMS_IS_MISSED',
    DATA_IS_MISSED: 'DATA_IS_MISSED',
    DOCUMENT_NOT_FOUND: 'DOCUMENT_NOT_FOUND',
    INVALID_DOCUMENT_STATUS: 'INVALID_DOCUMENT_STATUS',
    INVALID_SIGNATURE: 'INVALID_SIGNATURE',
    NOT_POSSIBLE_TO_USE_THE_SAME_SIGNATURE_TWICE: 'NOT_POSSIBLE_TO_USE_THE_SAME_SIGNATURE_TWICE',
};
