export const FILE_ERRORS = {
    FILES_ARE_REQUIRED: 'FILES_ARE_REQUIRED',
    INVALID_IMAGE_SIZE: 'INVALID_IMAGE_SIZE',
    INVALID_IMAGE_TYPE: 'INVALID_IMAGE_TYPE',
    TOO_MANY_FILES: 'TOO_MANY_FILES',
};
