export const RENT_ERRORS = {
    ROOM_ID_REQUIRED: 'ROOM_ID_REQUIRED',
    USER_ID_REQUIRED: 'USER_ID_REQUIRED',
    ISSUED_DATE_REQUIRED: 'ISSUED_DATE_REQUIRED',
    DUE_DATE_REQUIRED: 'DUE_DATE_REQUIRED',
    ISSUED_DATE_INVALID: 'ISSUED_DATE_INVALID',
    INVALID_DATES: 'INVALID_DATES',
    RENT_ALREADY_EXISTS: 'RENT_ALREADY_EXISTS',
    RENT_NOT_FOUND: 'RENT_NOT_FOUND',
};
