export const ROOM_ERRORS = {
    TITLE_IS_MISSED: 'TITLE_IS_MISSED',
    PRICE_IS_MISSED: 'PRICE_IS_MISSED',
    ROOM_TYPE_IS_MISSED: 'ROOM_TYPE_IS_MISSED',
    ADDRESS_IS_MISSED: 'ADDRESS_IS_MISSED',
    IS_COMMERCIAL_FLAG_IS_MISSED: 'IS_COMMERCIAL_FLAG_IS_MISSED',
    COORDINATES_IS_MISSED: 'COORDINATES_IS_MISSED',
    FLOOR_NUMBER_IS_MISSED: 'FLOOR_NUMBER_IS_MISSED',
    SECTION_TYPE_IS_MISSED: 'SECTION_TYPE_IS_MISSED',
};
