export const roomTypes = [
    {
        id: 'APARTMENT',
        fallbackName: 'Квартира',
        ru: 'Квартира',
        en: 'Apartment',
    },
    {
        id: 'PRIVATE_HOUSE',
        fallbackName: 'Частный дом',
        ru: 'Частный дом',
        en: 'Private House',
    },
    {
        id: 'STORE',
        fallbackName: 'Магазин',
        ru: 'Магазин',
        en: 'Store',
    },
    {
        id: 'RESTAURANT',
        fallbackName: 'Ресторан',
        ru: 'Ресторан',
        en: 'Restaurant',
    },
    {
        id: 'BAR',
        fallbackName: 'Бар',
        ru: 'Бар',
        en: 'Bar',
    },
];

export const sectionTypes = [
    {
        id: 'BEDROOM',
        ru: 'Спальня',
        en: 'Bedroom',
        fallbackName: 'Спальня',
        roomTypes: ['APARTMENT', 'PRIVATE_HOUSE'],
    },
    {
        id: 'LIVING_ROOM',
        ru: 'Гостиная',
        en: 'Living Room',
        fallbackName: 'Гостиная',
        roomTypes: ['APARTMENT', 'PRIVATE_HOUSE', 'STORE', 'RESTAURANT', 'BAR'],
    },
    {
        id: 'KITCHEN',
        ru: 'Кухня',
        en: 'Kitchen',
        fallbackName: 'Кухня',
        roomTypes: ['APARTMENT', 'PRIVATE_HOUSE', 'RESTAURANT'],
    },
    {
        id: 'RESTROOM',
        ru: 'С/У',
        en: 'Restroom',
        fallbackName: 'С/У',
        roomTypes: ['APARTMENT', 'PRIVATE_HOUSE', 'STORE', 'RESTAURANT', 'BAR'],
    },
    {
        id: 'BALCONY',
        ru: 'Балкон',
        en: 'Balcony',
        fallbackName: 'Балкон',
        roomTypes: ['APARTMENT', 'PRIVATE_HOUSE'],
    },
    {
        id: 'HALLWAY',
        ru: 'Прихожая',
        en: 'Hallway',
        fallbackName: 'Прихожая',
        roomTypes: ['APARTMENT', 'PRIVATE_HOUSE'],
    },
    {
        id: 'STORAGE',
        ru: 'Склад/Кладовка',
        en: 'Storage/Closet',
        fallbackName: 'Склад/Кладовка',
        roomTypes: ['APARTMENT', 'PRIVATE_HOUSE', 'STORE', 'RESTAURANT', 'BAR'],
    },
    {
        id: 'VERANDA',
        ru: 'Веранда',
        en: 'Veranda',
        fallbackName: 'Веранда',
        roomTypes: ['PRIVATE_HOUSE'],
    },
    {
        id: 'BASEMENT',
        ru: 'Подвал',
        en: 'Basement',
        fallbackName: 'Подвал',
        roomTypes: ['PRIVATE_HOUSE'],
    },
    {
        id: 'ATTIC',
        ru: 'Чердак',
        en: 'Attic',
        fallbackName: 'Чердак',
        roomTypes: ['PRIVATE_HOUSE'],
    },
    {
        id: 'YARD',
        ru: 'Сад/Двор',
        en: 'Garden/Yard',
        fallbackName: 'Сад/Двор',
        roomTypes: ['PRIVATE_HOUSE'],
    },
    {
        id: 'SALES_FLOOR',
        ru: 'Торговый зал',
        en: 'Sales Floor',
        fallbackName: 'Торговый зал',
        roomTypes: ['STORE'],
    },
    {
        id: 'CASH_REGISTER_FLOOR',
        ru: 'Кассовая зона',
        en: 'Cash Register Area',
        fallbackName: 'Кассовая зона',
        roomTypes: ['STORE'],
    },
    {
        id: 'RECEPTION',
        ru: 'Прихожая/Рецепция',
        en: 'Entrance/Reception',
        fallbackName: 'Прихожая/Рецепция',
        roomTypes: ['STORE', 'RESTAURANT', 'BAR'],
    },
    {
        id: 'ADVERTISING_SPACES',
        ru: 'Рекламные пространства',
        en: 'Advertising Spaces',
        fallbackName: 'Рекламные пространства',
        roomTypes: ['STORE', 'RESTAURANT', 'BAR'],
    },
    {
        id: 'GUEST_DINING_AREA',
        ru: 'Зал для гостей',
        en: 'Guest Dining Area',
        fallbackName: 'Зал для гостей',
        roomTypes: ['RESTAURANT'],
    },
    {
        id: 'BAR_AREA',
        ru: 'Барная зона',
        en: 'Bar Area',
        fallbackName: 'Барная зона',
        roomTypes: ['RESTAURANT', 'BAR'],
    },
    {
        id: 'WASHING_AREA',
        ru: 'Мойка',
        en: 'Washing Area',
        fallbackName: 'Мойка',
        roomTypes: ['RESTAURANT'],
    },
    {
        id: 'MANAGERS_OFFICE',
        ru: 'Кабинет управляющего',
        en: "Manager's Office",
        fallbackName: 'Кабинет управляющего',
        roomTypes: ['RESTAURANT'],
    },
    {
        id: 'STAFF_AREA',
        ru: 'Зона для персонала',
        en: 'Staff Area',
        fallbackName: 'Зона для персонала',
        roomTypes: ['RESTAURANT', 'BAR'],
    },
    {
        id: 'BAR_COUNTER',
        ru: 'Барная стойка',
        en: 'Bar Counter',
        fallbackName: 'Барная стойка',
        roomTypes: ['BAR'],
    },
    {
        id: 'LOUNGE_AREA',
        ru: 'Зона для отдыха',
        en: 'Lounge Area',
        fallbackName: 'Зона для отдыха',
        roomTypes: ['BAR'],
    },
    {
        id: 'DRINK_STORAGE',
        ru: 'Склад напитков',
        en: 'Drink Storage',
        fallbackName: 'Склад напитков',
        roomTypes: ['BAR'],
    },
];
