export enum RentStatus {
    OPENED = '2OPENED',
    PENDING = '4PENDING',
    PAID = '7PAID',
    REJECTED = '1REJECTED',
    CLOSED = '0CLOSED',
    ISSUES_ON_CHECK = '5ISSUES_ON_CHECK',
    ISSUES_REJECTED = '6ISSUES_REJECTED',
    IN_SIGNING_PROCESS = '3IN_SIGNING_PROCESS',
}
