export enum RentStatus {
    OPENED = 'OPENED',
    PENDING = 'PENDING',
    PAID = 'PAID',
    REJECTED = 'REJECTED',
    CLOSED = 'CLOSED',
    ISSUES_ON_CHECK = 'ISSUES_ON_CHECK',
    ISSUES_REJECTED = 'ISSUES_REJECTED',
    IN_SINGING_PROCESS = 'IN_SINGING_PROCESS',
}
