name: CI_CD
on:
  push:
    branches: [ "main" ]
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deps installation
        run: npm ci
      - name: Code linting
        run: npm run lint
  publishing:
    needs: [linting]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata for building
        id: metadata
        uses: docker/metadata-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: |
            ghcr.io/${{ github.repository }}
      - name: Build and push to registry
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
  deploying:
    needs: [publishing]
    runs-on: ubuntu-latest
    steps:
      - name: Pulling and rebuilding images on the host machine
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          password: ${{secrets.SSH_PRIVATE_KEY}}
          script: |
            cd ${{secrets.SSH_WORKDIR}}
            docker compose pull backend
            docker compose up -d --force-recreate postgres
            docker compose up -d --force-recreate backend
            
            
